services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    deploy:
      resources:
        limits:
          memory: 128M
    #restart: "on-failure"
  graph_db:
    image: neo4j:2025.10.1
    container_name: neo4j
    ports:
      - "7474:7474"
      - "7687:7687"
    environment:
      NEO4J_AUTH: "none"
      NEO4J_dbms_security_procedures_allowlist: "spatial.*"
      NEO4J_dbms_security_procedures_unrestricted: "spatial.*"
    volumes:
      - $HOME/neo4j/data:/data
      - $HOME/neo4j/plugins:/plugins
      - $HOME/neo4j/imports:/import


  kelder_api:
    build: .
    container_name: kelder_api
    privileged: true
    tty: true
    volumes:
      - /dev:/dev
      - ./logs:/app/logs
      - ./journey_history:/app/src/kelder_api/assets/
    devices:
      - /dev/gpiomem
      - /dev/mem
    cap_add:
      - SYS_RAWIO
    ports:
      - "8000:80"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
    env_file:
      - .env 
    extra_hosts:
      - "host.docker.internal:host-gateway"
    #restart: "on-failure"

  worker:
    build: .
    privileged: true
    volumes:
      - ./logs:/app/logs
      - ./journey_history:/app/src/kelder_api/assets/
    environment:
      REDIS_HOST: redis
    devices:
      - "/dev/ttyAMA0:/dev/ttyAMA0"
      - "/dev/ttyS0:/dev/ttyS0"
    command: [ "uv", "run", "python", "-m", "src.kelder_api.app.background_orchestrator" ]
    depends_on:
      - redis
    env_file:
      - .env 
    #restart: "on-failure"
